#!/usr/bin/env python3
"""
generate_motion_videos_kling.py — Med Escolha motion videos via NB2 → Kling.

For each motion poster (template 32-41) already generated by Nano Banana 2:
1. Upload the static poster image to catbox.moe (public URL)
2. Submit to Kling v2.1 Pro on kie.ai (image-to-video)
3. Download the resulting MP4 to videos/motion/

Cost: ~50 credits per 5s Kling clip. 10 videos = ~500 credits (~$5.00).
Time: ~6 minutes per generation, sequential.

Usage:
    python3 scripts/generate_motion_videos_kling.py
    python3 scripts/generate_motion_videos_kling.py --ids 32,36
    python3 scripts/generate_motion_videos_kling.py --duration 10
    python3 scripts/generate_motion_videos_kling.py --smoke
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path
from urllib.parse import urlparse

import requests

SCRIPT_DIR = Path(__file__).parent.resolve()
ROOT = SCRIPT_DIR.parent  # ads/med-escolha/
SINGLES_DIR = ROOT / "singles"
VIDEOS_DIR = ROOT / "videos" / "motion"

KEY_FILE = Path.home() / ".config" / "kie" / "api_key"

SUBMIT_URL = "https://api.kie.ai/api/v1/jobs/createTask"
STATUS_URL = "https://api.kie.ai/api/v1/jobs/recordInfo"
MODEL = "kling/v2-1-pro"

POLL_INTERVAL_S = 15
POLL_TIMEOUT_S = 900  # ~15 min upper bound

# (template_number, folder_basename, motion_prompt)
# Each motion_prompt tells Kling how to animate the static poster.
MOTION_DIRECTIVES = [
    (32, "motion-01-30-anos-travados",
     "subtle parallax zoom-in toward the bottom block, the words '30 anos travados' pulse with a soft glow once, the teal marker underline animates as if drawn with a hand, atmospheric digital particles drift slowly upward, calm contemplative pace"),
    (33, "motion-02-tres-conselheiros",
     "the three chat bubbles wobble subtly with slight tilts as if floating, the teal brushstrokes that cross them out animate progressively as if drawn in real time, gentle camera drift, the final headline pulses softly once"),
    (34, "motion-03-55-especialidades-grid",
     "the grid of 55 specialty cards subtly ripples in a wave pattern from left to right, the highlighted 'top 1' card pulses with a teal glow, gentle camera push-in toward the highlighted card, all other elements stay sharp and readable"),
    (35, "motion-04-math-10-vs-55",
     "the two number blocks pulse subtly with a glow on each impact, the teal 'vs' character has a gentle floating animation, the final headline 'a matemática não fecha' pulses once with emphasis, calm editorial pace"),
    (36, "motion-05-pricing-149",
     "the massive 'R$ 149' number pulses with a soft teal glow, atmospheric shimmer across the navy background, the lower '30 anos' text gently fades in stronger, the final tagline glows briefly on emphasis"),
    (37, "motion-06-phone-quiz",
     "the smartphone tilts subtly as if held in a hand, the contradictory results on screen flicker between three states with a glitch effect, the red X overlay pulses, then the headline below pulses with emphasis, CTA button has a soft glow pulse"),
    (38, "motion-07-3-verdades",
     "the three verdade cards reveal sequentially with subtle slide-up motion, each marker underline animates as if hand-drawn, gentle floating motion on each card after it appears, CTA button glows softly at the end"),
    (39, "motion-08-calendar-changing",
     "the handwritten specialty names inside each day card jitter subtly as if being rewritten, the marker scribbles and crossings-out animate, the whole calendar shakes briefly on emphasis, then the final headline pulses with frustration energy"),
    (40, "motion-09-ranking-narrativa",
     "the smartphone subtly floats with handheld micro-sway, the top match card pulses with a teal glow, the narrative text below scrolls slowly upward, CTA button glows softly, premium product reveal feel"),
    (41, "motion-10-fim-do-achismo",
     "the teal marker brushstroke crosses out 'achismo.' diagonally as if drawn in real time, then 'método.' pulses brighter with confidence, atmospheric particles drift upward, CTA button glows softly at the end, brand manifesto energy"),
]


def load_api_key() -> str:
    if not KEY_FILE.exists():
        sys.exit(f"error: api key not found at {KEY_FILE}")
    return KEY_FILE.read_text().strip()


def upload_image_public(image_path: Path) -> str:
    """Upload image to catbox.moe (primary) or 0x0.st (fallback). Returns public URL."""
    print(f"  ↑ uploading {image_path.name}...", end=" ", flush=True)
    # Try catbox
    try:
        result = subprocess.run(
            ["curl", "-fsSL", "-F", "reqtype=fileupload", "-F", f"fileToUpload=@{image_path}",
             "https://catbox.moe/user/api.php"],
            capture_output=True, text=True, timeout=60,
        )
        if result.returncode == 0:
            url = result.stdout.strip()
            if url.startswith("http"):
                print(f"→ {url} (catbox)")
                return url
    except Exception:
        pass
    # Fallback: 0x0.st
    try:
        result = subprocess.run(
            ["curl", "-fsSL", "-F", f"file=@{image_path}", "https://0x0.st"],
            capture_output=True, text=True, timeout=60,
        )
        if result.returncode == 0:
            url = result.stdout.strip()
            if url.startswith("http"):
                print(f"→ {url} (0x0)")
                return url
    except Exception:
        pass
    raise RuntimeError(f"all image upload hosts failed for {image_path.name}")


def submit_kling(api_key: str, image_url: str, motion_prompt: str,
                 duration: str, aspect_ratio: str) -> str:
    body = {
        "model": MODEL,
        "input": {
            "prompt": motion_prompt,
            "image_url": image_url,
            "duration": duration,
            "aspectRatio": aspect_ratio,
        },
    }
    r = requests.post(
        SUBMIT_URL,
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
        json=body, timeout=60,
    )
    r.raise_for_status()
    bj = r.json()
    if bj.get("code") != 200:
        raise RuntimeError(f"kling submit error {bj.get('code')}: {bj.get('msg')}")
    task_id = (bj.get("data") or {}).get("taskId")
    if not task_id:
        raise RuntimeError(f"no taskId: {bj}")
    return task_id


def poll_kling(api_key: str, task_id: str) -> str:
    deadline = time.time() + POLL_TIMEOUT_S
    while time.time() < deadline:
        time.sleep(POLL_INTERVAL_S)
        r = requests.get(
            STATUS_URL,
            headers={"Authorization": f"Bearer {api_key}"},
            params={"taskId": task_id}, timeout=30,
        )
        if r.status_code != 200:
            continue
        data = r.json().get("data") or {}
        state = (data.get("state") or "").lower()
        if state in ("success", "completed", "done"):
            rj = data.get("resultJson")
            if isinstance(rj, str):
                parsed = json.loads(rj)
                urls = parsed.get("resultUrls") or []
                if urls:
                    return urls[0]
            raise RuntimeError(f"success but no urls: {data}")
        if state in ("failed", "error", "fail"):
            raise RuntimeError(f"kling failed: {data}")
    raise TimeoutError(f"kling job {task_id} timeout after {POLL_TIMEOUT_S}s")


def download_video(url: str, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    r = requests.get(url, stream=True, timeout=300)
    r.raise_for_status()
    with open(dest, "wb") as f:
        for chunk in r.iter_content(chunk_size=8192):
            f.write(chunk)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--ids", type=str, default="", help="Comma-separated template numbers")
    p.add_argument("--duration", type=str, default="5", help="5 or 10 seconds")
    p.add_argument("--aspect-ratio", type=str, default="9:16")
    p.add_argument("--smoke", action="store_true", help="Only run the first")
    args = p.parse_args()

    api_key = load_api_key()

    if args.ids.strip():
        wanted = {int(x) for x in args.ids.split(",") if x.strip()}
        selected = [d for d in MOTION_DIRECTIVES if d[0] in wanted]
    elif args.smoke:
        selected = MOTION_DIRECTIVES[:1]
    else:
        selected = MOTION_DIRECTIVES

    print(f"running {len(selected)} motion video(s) | model={MODEL} | duration={args.duration}s")
    cost_per = 50 if args.duration == "5" else 100
    print(f"estimated cost: ~${len(selected) * cost_per * 0.01:.2f}")

    image_url_cache: dict[str, str] = {}
    saved, errors = [], []

    for tpl_num, video_basename, motion_prompt in selected:
        # Find the poster image
        candidates = list(SINGLES_DIR.glob(f"{tpl_num:02d}-*"))
        if not candidates:
            errors.append(f"[{tpl_num}] poster folder not found")
            continue
        poster_dir = candidates[0]
        poster = poster_dir / "v1.png"
        if not poster.exists():
            errors.append(f"[{tpl_num}] {poster} not found")
            continue

        print(f"\n[{tpl_num}] {video_basename}")
        try:
            # Upload (cached per file)
            if str(poster) not in image_url_cache:
                image_url_cache[str(poster)] = upload_image_public(poster)
            image_url = image_url_cache[str(poster)]

            print(f"  → submitting kling...")
            task_id = submit_kling(api_key, image_url, motion_prompt, args.duration, args.aspect_ratio)
            print(f"     task_id={task_id}, polling (~6min)...")
            mp4_url = poll_kling(api_key, task_id)

            out_dir = VIDEOS_DIR / video_basename
            out_dir.mkdir(parents=True, exist_ok=True)
            dest = out_dir / "video.mp4"
            (out_dir / "motion_prompt.txt").write_text(motion_prompt + "\n")
            download_video(mp4_url, dest)
            saved.append(dest)
            print(f"     ✓ saved {dest.relative_to(ROOT)}")
        except Exception as e:
            print(f"  ! ERROR: {e}")
            errors.append(f"[{tpl_num}] {video_basename}: {e}")

    print(f"\n=== done. saved {len(saved)} video(s). errors: {len(errors)}")
    for e in errors:
        print(f"  - {e}")

    return 0 if not errors else 1


if __name__ == "__main__":
    sys.exit(main())
